apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kubectl
spec:
  params:
  - name: SCRIPT
    description: Argumentos do kubectl
    type: string
    default: "kubectl help"
  steps:
    - name: oc
      image: bitnami/kubectl
      script: |
        #! /usr/bin/env bash
        $(params.SCRIPT)
  workspaces:
    - name: source