apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: task-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: task-role
subjects:
- kind: ServiceAccount
  name: tekton-deployer-sa