apiVersion: rbac.authorization.k8s.io/v1 
kind: Role
metadata:
  name: task-role 
rules:
  - apiGroups: 
    - ""
    resources: 
    - pods
    - services
    - endpoints
    - configmaps
    - secrets
    verbs: 
    - "*"
  - apiGroups: 
    - apps
    resources:
    - deployments 
    - replicasets
    verbs: 
    - "*"
  - apiGroups: 
    - ""
    resources: 
    - pods
    verbs: 
    - get
  - apiGroups: 
    - apps
    resources:
    - replicasets
    verbs: 
    - get