apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-credentials
  annotations:
    tekton.dev/docker-0: https://index.docker.io/v1/
type: kubernetes.io/basic-auth
stringData:
  username: '<EMAIL>'
  password: '<SENHA>'

# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: tekton-registry-sa
# secrets:
#   - name: dockerhub-credentials